general.live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
dynamic_padding = false

opacity = 0.8

[window.padding]
x = 20
y = 15

#colors.draw_bold_text_with_bright_colors = true

# Cyberpunk-Neon colours
[colors.primary]
background = '0x000b1e'
foreground = '0x0abdc6'

# Uncomment the following block if you want to specify cursor colors
# [colors.cursor]
# text = '0x2e2e2d'
# cursor = '0xffffff'

[colors.normal]
black = '0x123e7c'
red = '0xff0000'
green = '0x3fff2d'
yellow = '0xfee801'
blue = '0x4166f5'
magenta = '0xff00ff'
cyan = '0x0abdc6'
white = '0xd7d7d5'

[colors.bright]
black = '0x1c61c2'
red = '0xff0000'
green = '0x3fff2d'
yellow = '0xfee801'
blue = '0x00ff00'
magenta = '0xff00ff'
cyan = '0x0abdc6'
white = '0xd7d7d5'

[colors.dim]
black = '0x1c61c2'
red = '0xff0000'
green = '0x3fff2d'
yellow = '0xfee801'
blue = '0x123e7c'
magenta = '0x76ff7a'
cyan = '0x0abdc6'
white = '0xd7d7d5'
